workflows:
  android-workflow:
    name: Android WebView Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate missing Android folder
        script: |
          # Creates a temporary project with a custom Application ID
          flutter create --platforms=android --org org.sscgroup.webview temp_project
          
          # Moves the newly generated android folder into your project
          mv temp_project/android ./android
          
          # Deletes the temporary project to keep the workspace clean
          rm -rf temp_project
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Build Android App Bundle (For Google Play Store)
        script: |
          flutter build appbundle --release
          
      - name: Build Android APK (For Direct Phone Testing)
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
